(define (problem uav_problem_u1_r0_l5_p8_c25_g20_ct3)
(:domain uav-domain)
(:objects
	uav1 - uav
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	food - contents
	medicine - contents
	water - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
)
(:init
	(at crate1 depot)
	(contains crate1 food)
	(at crate2 depot)
	(contains crate2 food)
	(at crate3 depot)
	(contains crate3 food)
	(at crate4 depot)
	(contains crate4 food)
	(at crate5 depot)
	(contains crate5 food)
	(at crate6 depot)
	(contains crate6 food)
	(at crate7 depot)
	(contains crate7 food)
	(at crate8 depot)
	(contains crate8 food)
	(at crate9 depot)
	(contains crate9 medicine)
	(at crate10 depot)
	(contains crate10 medicine)
	(at crate11 depot)
	(contains crate11 medicine)
	(at crate12 depot)
	(contains crate12 medicine)
	(at crate13 depot)
	(contains crate13 medicine)
	(at crate14 depot)
	(contains crate14 medicine)
	(at crate15 depot)
	(contains crate15 medicine)
	(at crate16 depot)
	(contains crate16 medicine)
	(at crate17 depot)
	(contains crate17 water)
	(at crate18 depot)
	(contains crate18 water)
	(at crate19 depot)
	(contains crate19 water)
	(at crate20 depot)
	(contains crate20 water)
	(at crate21 depot)
	(contains crate21 water)
	(at crate22 depot)
	(contains crate22 water)
	(at crate23 depot)
	(contains crate23 water)
	(at crate24 depot)
	(contains crate24 water)
	(at crate25 depot)
	(contains crate25 water)
	(at uav1 depot)
	(free uav1)
	(at person1 loc3)
	(at person2 loc2)
	(at person3 loc2)
	(at person4 loc5)
	(at person5 loc5)
	(at person6 loc3)
	(at person7 loc5)
	(at person8 loc4)
	(wants person1 food)
	(wants person1 water)
	(wants person2 food)
	(wants person2 medicine)
	(wants person2 water)
	(wants person3 water)
	(wants person4 food)
	(wants person4 medicine)
	(wants person4 water)
	(wants person5 food)
	(wants person5 medicine)
	(wants person5 water)
	(wants person6 food)
	(wants person6 medicine)
	(wants person6 water)
	(wants person7 food)
	(wants person7 medicine)
	(wants person8 food)
	(wants person8 medicine)
	(wants person8 water)
)
(:goal (and

	(at uav1 depot)
	(has person1 food)
	(has person1 water)
	(has person2 food)
	(has person2 medicine)
	(has person2 water)
	(has person3 water)
	(has person4 food)
	(has person4 medicine)
	(has person4 water)
	(has person5 food)
	(has person5 medicine)
	(has person5 water)
	(has person6 food)
	(has person6 medicine)
	(has person6 water)
	(has person7 food)
	(has person7 medicine)
	(has person8 food)
	(has person8 medicine)
	(has person8 water)
	))
)
