(define (problem uav_problem_u1_r0_l5_p8_c50_g24_ct3)
(:domain uav-domain)
(:objects
	uav1 - uav
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	food - contents
	medicine - contents
	water - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
)
(:init
	(at crate1 depot)
	(contains crate1 food)
	(at crate2 depot)
	(contains crate2 food)
	(at crate3 depot)
	(contains crate3 food)
	(at crate4 depot)
	(contains crate4 food)
	(at crate5 depot)
	(contains crate5 food)
	(at crate6 depot)
	(contains crate6 food)
	(at crate7 depot)
	(contains crate7 food)
	(at crate8 depot)
	(contains crate8 food)
	(at crate9 depot)
	(contains crate9 food)
	(at crate10 depot)
	(contains crate10 food)
	(at crate11 depot)
	(contains crate11 food)
	(at crate12 depot)
	(contains crate12 food)
	(at crate13 depot)
	(contains crate13 food)
	(at crate14 depot)
	(contains crate14 food)
	(at crate15 depot)
	(contains crate15 food)
	(at crate16 depot)
	(contains crate16 food)
	(at crate17 depot)
	(contains crate17 medicine)
	(at crate18 depot)
	(contains crate18 medicine)
	(at crate19 depot)
	(contains crate19 medicine)
	(at crate20 depot)
	(contains crate20 medicine)
	(at crate21 depot)
	(contains crate21 medicine)
	(at crate22 depot)
	(contains crate22 medicine)
	(at crate23 depot)
	(contains crate23 medicine)
	(at crate24 depot)
	(contains crate24 medicine)
	(at crate25 depot)
	(contains crate25 medicine)
	(at crate26 depot)
	(contains crate26 medicine)
	(at crate27 depot)
	(contains crate27 medicine)
	(at crate28 depot)
	(contains crate28 medicine)
	(at crate29 depot)
	(contains crate29 medicine)
	(at crate30 depot)
	(contains crate30 medicine)
	(at crate31 depot)
	(contains crate31 medicine)
	(at crate32 depot)
	(contains crate32 water)
	(at crate33 depot)
	(contains crate33 water)
	(at crate34 depot)
	(contains crate34 water)
	(at crate35 depot)
	(contains crate35 water)
	(at crate36 depot)
	(contains crate36 water)
	(at crate37 depot)
	(contains crate37 water)
	(at crate38 depot)
	(contains crate38 water)
	(at crate39 depot)
	(contains crate39 water)
	(at crate40 depot)
	(contains crate40 water)
	(at crate41 depot)
	(contains crate41 water)
	(at crate42 depot)
	(contains crate42 water)
	(at crate43 depot)
	(contains crate43 water)
	(at crate44 depot)
	(contains crate44 water)
	(at crate45 depot)
	(contains crate45 water)
	(at crate46 depot)
	(contains crate46 water)
	(at crate47 depot)
	(contains crate47 water)
	(at crate48 depot)
	(contains crate48 water)
	(at crate49 depot)
	(contains crate49 water)
	(at crate50 depot)
	(contains crate50 water)
	(at uav1 depot)
	(free uav1)
	(at person1 loc3)
	(at person2 loc4)
	(at person3 loc3)
	(at person4 loc4)
	(at person5 loc5)
	(at person6 loc4)
	(at person7 loc2)
	(at person8 loc2)
	(wants person1 food)
	(wants person1 medicine)
	(wants person1 water)
	(wants person2 food)
	(wants person2 medicine)
	(wants person2 water)
	(wants person3 food)
	(wants person3 medicine)
	(wants person3 water)
	(wants person4 food)
	(wants person4 medicine)
	(wants person4 water)
	(wants person5 food)
	(wants person5 medicine)
	(wants person5 water)
	(wants person6 food)
	(wants person6 medicine)
	(wants person6 water)
	(wants person7 food)
	(wants person7 medicine)
	(wants person7 water)
	(wants person8 food)
	(wants person8 medicine)
	(wants person8 water)
)
(:goal (and

	(at uav1 depot)
	(has person1 food)
	(has person1 medicine)
	(has person1 water)
	(has person2 food)
	(has person2 medicine)
	(has person2 water)
	(has person3 food)
	(has person3 medicine)
	(has person3 water)
	(has person4 food)
	(has person4 medicine)
	(has person4 water)
	(has person5 food)
	(has person5 medicine)
	(has person5 water)
	(has person6 food)
	(has person6 medicine)
	(has person6 water)
	(has person7 food)
	(has person7 medicine)
	(has person7 water)
	(has person8 food)
	(has person8 medicine)
	(has person8 water)
	))
)
