(define (problem uav_problem_u1_r0_l65_p60_c100_g85_ct3)
(:domain uav-domain)
(:objects
	uav1 - uav
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	loc51 - location
	loc52 - location
	loc53 - location
	loc54 - location
	loc55 - location
	loc56 - location
	loc57 - location
	loc58 - location
	loc59 - location
	loc60 - location
	loc61 - location
	loc62 - location
	loc63 - location
	loc64 - location
	loc65 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	crate52 - crate
	crate53 - crate
	crate54 - crate
	crate55 - crate
	crate56 - crate
	crate57 - crate
	crate58 - crate
	crate59 - crate
	crate60 - crate
	crate61 - crate
	crate62 - crate
	crate63 - crate
	crate64 - crate
	crate65 - crate
	crate66 - crate
	crate67 - crate
	crate68 - crate
	crate69 - crate
	crate70 - crate
	crate71 - crate
	crate72 - crate
	crate73 - crate
	crate74 - crate
	crate75 - crate
	crate76 - crate
	crate77 - crate
	crate78 - crate
	crate79 - crate
	crate80 - crate
	crate81 - crate
	crate82 - crate
	crate83 - crate
	crate84 - crate
	crate85 - crate
	crate86 - crate
	crate87 - crate
	crate88 - crate
	crate89 - crate
	crate90 - crate
	crate91 - crate
	crate92 - crate
	crate93 - crate
	crate94 - crate
	crate95 - crate
	crate96 - crate
	crate97 - crate
	crate98 - crate
	crate99 - crate
	crate100 - crate
	food - contents
	medicine - contents
	water - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
	person51 - person
	person52 - person
	person53 - person
	person54 - person
	person55 - person
	person56 - person
	person57 - person
	person58 - person
	person59 - person
	person60 - person
)
(:init
	(at crate1 depot)
	(contains crate1 food)
	(at crate2 depot)
	(contains crate2 food)
	(at crate3 depot)
	(contains crate3 food)
	(at crate4 depot)
	(contains crate4 food)
	(at crate5 depot)
	(contains crate5 food)
	(at crate6 depot)
	(contains crate6 food)
	(at crate7 depot)
	(contains crate7 food)
	(at crate8 depot)
	(contains crate8 food)
	(at crate9 depot)
	(contains crate9 food)
	(at crate10 depot)
	(contains crate10 food)
	(at crate11 depot)
	(contains crate11 food)
	(at crate12 depot)
	(contains crate12 food)
	(at crate13 depot)
	(contains crate13 food)
	(at crate14 depot)
	(contains crate14 food)
	(at crate15 depot)
	(contains crate15 food)
	(at crate16 depot)
	(contains crate16 food)
	(at crate17 depot)
	(contains crate17 food)
	(at crate18 depot)
	(contains crate18 food)
	(at crate19 depot)
	(contains crate19 food)
	(at crate20 depot)
	(contains crate20 food)
	(at crate21 depot)
	(contains crate21 food)
	(at crate22 depot)
	(contains crate22 food)
	(at crate23 depot)
	(contains crate23 food)
	(at crate24 depot)
	(contains crate24 food)
	(at crate25 depot)
	(contains crate25 food)
	(at crate26 depot)
	(contains crate26 food)
	(at crate27 depot)
	(contains crate27 food)
	(at crate28 depot)
	(contains crate28 food)
	(at crate29 depot)
	(contains crate29 food)
	(at crate30 depot)
	(contains crate30 food)
	(at crate31 depot)
	(contains crate31 food)
	(at crate32 depot)
	(contains crate32 food)
	(at crate33 depot)
	(contains crate33 food)
	(at crate34 depot)
	(contains crate34 food)
	(at crate35 depot)
	(contains crate35 food)
	(at crate36 depot)
	(contains crate36 food)
	(at crate37 depot)
	(contains crate37 medicine)
	(at crate38 depot)
	(contains crate38 medicine)
	(at crate39 depot)
	(contains crate39 medicine)
	(at crate40 depot)
	(contains crate40 medicine)
	(at crate41 depot)
	(contains crate41 medicine)
	(at crate42 depot)
	(contains crate42 medicine)
	(at crate43 depot)
	(contains crate43 medicine)
	(at crate44 depot)
	(contains crate44 medicine)
	(at crate45 depot)
	(contains crate45 medicine)
	(at crate46 depot)
	(contains crate46 medicine)
	(at crate47 depot)
	(contains crate47 medicine)
	(at crate48 depot)
	(contains crate48 medicine)
	(at crate49 depot)
	(contains crate49 medicine)
	(at crate50 depot)
	(contains crate50 medicine)
	(at crate51 depot)
	(contains crate51 medicine)
	(at crate52 depot)
	(contains crate52 medicine)
	(at crate53 depot)
	(contains crate53 water)
	(at crate54 depot)
	(contains crate54 water)
	(at crate55 depot)
	(contains crate55 water)
	(at crate56 depot)
	(contains crate56 water)
	(at crate57 depot)
	(contains crate57 water)
	(at crate58 depot)
	(contains crate58 water)
	(at crate59 depot)
	(contains crate59 water)
	(at crate60 depot)
	(contains crate60 water)
	(at crate61 depot)
	(contains crate61 water)
	(at crate62 depot)
	(contains crate62 water)
	(at crate63 depot)
	(contains crate63 water)
	(at crate64 depot)
	(contains crate64 water)
	(at crate65 depot)
	(contains crate65 water)
	(at crate66 depot)
	(contains crate66 water)
	(at crate67 depot)
	(contains crate67 water)
	(at crate68 depot)
	(contains crate68 water)
	(at crate69 depot)
	(contains crate69 water)
	(at crate70 depot)
	(contains crate70 water)
	(at crate71 depot)
	(contains crate71 water)
	(at crate72 depot)
	(contains crate72 water)
	(at crate73 depot)
	(contains crate73 water)
	(at crate74 depot)
	(contains crate74 water)
	(at crate75 depot)
	(contains crate75 water)
	(at crate76 depot)
	(contains crate76 water)
	(at crate77 depot)
	(contains crate77 water)
	(at crate78 depot)
	(contains crate78 water)
	(at crate79 depot)
	(contains crate79 water)
	(at crate80 depot)
	(contains crate80 water)
	(at crate81 depot)
	(contains crate81 water)
	(at crate82 depot)
	(contains crate82 water)
	(at crate83 depot)
	(contains crate83 water)
	(at crate84 depot)
	(contains crate84 water)
	(at crate85 depot)
	(contains crate85 water)
	(at crate86 depot)
	(contains crate86 water)
	(at crate87 depot)
	(contains crate87 water)
	(at crate88 depot)
	(contains crate88 water)
	(at crate89 depot)
	(contains crate89 water)
	(at crate90 depot)
	(contains crate90 water)
	(at crate91 depot)
	(contains crate91 water)
	(at crate92 depot)
	(contains crate92 water)
	(at crate93 depot)
	(contains crate93 water)
	(at crate94 depot)
	(contains crate94 water)
	(at crate95 depot)
	(contains crate95 water)
	(at crate96 depot)
	(contains crate96 water)
	(at crate97 depot)
	(contains crate97 water)
	(at crate98 depot)
	(contains crate98 water)
	(at crate99 depot)
	(contains crate99 water)
	(at crate100 depot)
	(contains crate100 water)
	(at uav1 depot)
	(free uav1)
	(at person1 loc2)
	(at person2 loc59)
	(at person3 loc13)
	(at person4 loc10)
	(at person5 loc28)
	(at person6 loc65)
	(at person7 loc34)
	(at person8 loc17)
	(at person9 loc45)
	(at person10 loc9)
	(at person11 loc32)
	(at person12 loc48)
	(at person13 loc37)
	(at person14 loc21)
	(at person15 loc57)
	(at person16 loc39)
	(at person17 loc2)
	(at person18 loc39)
	(at person19 loc14)
	(at person20 loc18)
	(at person21 loc34)
	(at person22 loc15)
	(at person23 loc14)
	(at person24 loc20)
	(at person25 loc35)
	(at person26 loc37)
	(at person27 loc27)
	(at person28 loc44)
	(at person29 loc27)
	(at person30 loc34)
	(at person31 loc65)
	(at person32 loc63)
	(at person33 loc33)
	(at person34 loc7)
	(at person35 loc12)
	(at person36 loc55)
	(at person37 loc36)
	(at person38 loc6)
	(at person39 loc1)
	(at person40 loc43)
	(at person41 loc17)
	(at person42 loc34)
	(at person43 loc21)
	(at person44 loc57)
	(at person45 loc55)
	(at person46 loc2)
	(at person47 loc15)
	(at person48 loc10)
	(at person49 loc20)
	(at person50 loc5)
	(at person51 loc48)
	(at person52 loc19)
	(at person53 loc56)
	(at person54 loc17)
	(at person55 loc6)
	(at person56 loc40)
	(at person57 loc47)
	(at person58 loc6)
	(at person59 loc46)
	(at person60 loc27)
	(wants person1 food)
	(wants person1 water)
	(wants person2 water)
	(wants person4 food)
	(wants person4 water)
	(wants person5 food)
	(wants person5 medicine)
	(wants person5 water)
	(wants person6 food)
	(wants person7 food)
	(wants person7 water)
	(wants person8 medicine)
	(wants person8 water)
	(wants person9 water)
	(wants person10 water)
	(wants person11 food)
	(wants person11 medicine)
	(wants person11 water)
	(wants person13 food)
	(wants person13 water)
	(wants person14 food)
	(wants person14 water)
	(wants person15 food)
	(wants person16 food)
	(wants person16 medicine)
	(wants person16 water)
	(wants person17 water)
	(wants person19 medicine)
	(wants person20 water)
	(wants person21 food)
	(wants person22 food)
	(wants person24 food)
	(wants person25 water)
	(wants person26 food)
	(wants person26 medicine)
	(wants person26 water)
	(wants person27 water)
	(wants person28 food)
	(wants person28 water)
	(wants person29 food)
	(wants person29 water)
	(wants person30 water)
	(wants person31 water)
	(wants person32 food)
	(wants person33 food)
	(wants person33 medicine)
	(wants person33 water)
	(wants person34 water)
	(wants person35 food)
	(wants person35 water)
	(wants person36 food)
	(wants person37 medicine)
	(wants person38 food)
	(wants person38 water)
	(wants person39 food)
	(wants person39 medicine)
	(wants person40 food)
	(wants person42 medicine)
	(wants person42 water)
	(wants person43 medicine)
	(wants person43 water)
	(wants person44 water)
	(wants person45 food)
	(wants person45 water)
	(wants person46 medicine)
	(wants person46 water)
	(wants person47 medicine)
	(wants person48 water)
	(wants person49 food)
	(wants person49 medicine)
	(wants person49 water)
	(wants person50 food)
	(wants person50 water)
	(wants person51 water)
	(wants person53 food)
	(wants person54 food)
	(wants person55 food)
	(wants person56 food)
	(wants person56 medicine)
	(wants person56 water)
	(wants person57 medicine)
	(wants person57 water)
	(wants person58 food)
	(wants person59 food)
	(wants person60 water)
)
(:goal (and

	(at uav1 depot)
	(has person1 food)
	(has person1 water)
	(has person2 water)
	(has person4 food)
	(has person4 water)
	(has person5 food)
	(has person5 medicine)
	(has person5 water)
	(has person6 food)
	(has person7 food)
	(has person7 water)
	(has person8 medicine)
	(has person8 water)
	(has person9 water)
	(has person10 water)
	(has person11 food)
	(has person11 medicine)
	(has person11 water)
	(has person13 food)
	(has person13 water)
	(has person14 food)
	(has person14 water)
	(has person15 food)
	(has person16 food)
	(has person16 medicine)
	(has person16 water)
	(has person17 water)
	(has person19 medicine)
	(has person20 water)
	(has person21 food)
	(has person22 food)
	(has person24 food)
	(has person25 water)
	(has person26 food)
	(has person26 medicine)
	(has person26 water)
	(has person27 water)
	(has person28 food)
	(has person28 water)
	(has person29 food)
	(has person29 water)
	(has person30 water)
	(has person31 water)
	(has person32 food)
	(has person33 food)
	(has person33 medicine)
	(has person33 water)
	(has person34 water)
	(has person35 food)
	(has person35 water)
	(has person36 food)
	(has person37 medicine)
	(has person38 food)
	(has person38 water)
	(has person39 food)
	(has person39 medicine)
	(has person40 food)
	(has person42 medicine)
	(has person42 water)
	(has person43 medicine)
	(has person43 water)
	(has person44 water)
	(has person45 food)
	(has person45 water)
	(has person46 medicine)
	(has person46 water)
	(has person47 medicine)
	(has person48 water)
	(has person49 food)
	(has person49 medicine)
	(has person49 water)
	(has person50 food)
	(has person50 water)
	(has person51 water)
	(has person53 food)
	(has person54 food)
	(has person55 food)
	(has person56 food)
	(has person56 medicine)
	(has person56 water)
	(has person57 medicine)
	(has person57 water)
	(has person58 food)
	(has person59 food)
	(has person60 water)
	))
)
