(define (problem uav_problem_u1_r0_l30_p30_c50_g50_ct3)
(:domain uav-domain)
(:objects
	uav1 - uav
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	food - contents
	medicine - contents
	water - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
)
(:init
	(at crate1 depot)
	(contains crate1 food)
	(at crate2 depot)
	(contains crate2 food)
	(at crate3 depot)
	(contains crate3 medicine)
	(at crate4 depot)
	(contains crate4 medicine)
	(at crate5 depot)
	(contains crate5 medicine)
	(at crate6 depot)
	(contains crate6 medicine)
	(at crate7 depot)
	(contains crate7 medicine)
	(at crate8 depot)
	(contains crate8 medicine)
	(at crate9 depot)
	(contains crate9 medicine)
	(at crate10 depot)
	(contains crate10 medicine)
	(at crate11 depot)
	(contains crate11 medicine)
	(at crate12 depot)
	(contains crate12 medicine)
	(at crate13 depot)
	(contains crate13 medicine)
	(at crate14 depot)
	(contains crate14 medicine)
	(at crate15 depot)
	(contains crate15 medicine)
	(at crate16 depot)
	(contains crate16 medicine)
	(at crate17 depot)
	(contains crate17 medicine)
	(at crate18 depot)
	(contains crate18 medicine)
	(at crate19 depot)
	(contains crate19 medicine)
	(at crate20 depot)
	(contains crate20 medicine)
	(at crate21 depot)
	(contains crate21 water)
	(at crate22 depot)
	(contains crate22 water)
	(at crate23 depot)
	(contains crate23 water)
	(at crate24 depot)
	(contains crate24 water)
	(at crate25 depot)
	(contains crate25 water)
	(at crate26 depot)
	(contains crate26 water)
	(at crate27 depot)
	(contains crate27 water)
	(at crate28 depot)
	(contains crate28 water)
	(at crate29 depot)
	(contains crate29 water)
	(at crate30 depot)
	(contains crate30 water)
	(at crate31 depot)
	(contains crate31 water)
	(at crate32 depot)
	(contains crate32 water)
	(at crate33 depot)
	(contains crate33 water)
	(at crate34 depot)
	(contains crate34 water)
	(at crate35 depot)
	(contains crate35 water)
	(at crate36 depot)
	(contains crate36 water)
	(at crate37 depot)
	(contains crate37 water)
	(at crate38 depot)
	(contains crate38 water)
	(at crate39 depot)
	(contains crate39 water)
	(at crate40 depot)
	(contains crate40 water)
	(at crate41 depot)
	(contains crate41 water)
	(at crate42 depot)
	(contains crate42 water)
	(at crate43 depot)
	(contains crate43 water)
	(at crate44 depot)
	(contains crate44 water)
	(at crate45 depot)
	(contains crate45 water)
	(at crate46 depot)
	(contains crate46 water)
	(at crate47 depot)
	(contains crate47 water)
	(at crate48 depot)
	(contains crate48 water)
	(at crate49 depot)
	(contains crate49 water)
	(at crate50 depot)
	(contains crate50 water)
	(at uav1 depot)
	(free uav1)
	(at person1 loc15)
	(at person2 loc14)
	(at person3 loc2)
	(at person4 loc7)
	(at person5 loc27)
	(at person6 loc14)
	(at person7 loc13)
	(at person8 loc29)
	(at person9 loc25)
	(at person10 loc19)
	(at person11 loc23)
	(at person12 loc1)
	(at person13 loc28)
	(at person14 loc29)
	(at person15 loc25)
	(at person16 loc19)
	(at person17 loc13)
	(at person18 loc16)
	(at person19 loc1)
	(at person20 loc12)
	(at person21 loc10)
	(at person22 loc25)
	(at person23 loc13)
	(at person24 loc28)
	(at person25 loc29)
	(at person26 loc27)
	(at person27 loc14)
	(at person28 loc18)
	(at person29 loc24)
	(at person30 loc24)
	(wants person1 water)
	(wants person2 water)
	(wants person3 medicine)
	(wants person3 water)
	(wants person4 medicine)
	(wants person4 water)
	(wants person5 water)
	(wants person6 medicine)
	(wants person6 water)
	(wants person7 water)
	(wants person8 medicine)
	(wants person8 water)
	(wants person9 water)
	(wants person10 medicine)
	(wants person10 water)
	(wants person11 water)
	(wants person12 water)
	(wants person13 medicine)
	(wants person13 water)
	(wants person14 water)
	(wants person15 water)
	(wants person16 water)
	(wants person17 medicine)
	(wants person17 water)
	(wants person18 water)
	(wants person19 food)
	(wants person19 medicine)
	(wants person19 water)
	(wants person20 medicine)
	(wants person20 water)
	(wants person21 medicine)
	(wants person21 water)
	(wants person22 medicine)
	(wants person22 water)
	(wants person23 food)
	(wants person23 medicine)
	(wants person23 water)
	(wants person24 medicine)
	(wants person24 water)
	(wants person25 medicine)
	(wants person25 water)
	(wants person26 medicine)
	(wants person26 water)
	(wants person27 medicine)
	(wants person27 water)
	(wants person28 medicine)
	(wants person28 water)
	(wants person29 medicine)
	(wants person29 water)
	(wants person30 water)
)
(:goal (and

	(at uav1 depot)
	(has person1 water)
	(has person2 water)
	(has person3 medicine)
	(has person3 water)
	(has person4 medicine)
	(has person4 water)
	(has person5 water)
	(has person6 medicine)
	(has person6 water)
	(has person7 water)
	(has person8 medicine)
	(has person8 water)
	(has person9 water)
	(has person10 medicine)
	(has person10 water)
	(has person11 water)
	(has person12 water)
	(has person13 medicine)
	(has person13 water)
	(has person14 water)
	(has person15 water)
	(has person16 water)
	(has person17 medicine)
	(has person17 water)
	(has person18 water)
	(has person19 food)
	(has person19 medicine)
	(has person19 water)
	(has person20 medicine)
	(has person20 water)
	(has person21 medicine)
	(has person21 water)
	(has person22 medicine)
	(has person22 water)
	(has person23 food)
	(has person23 medicine)
	(has person23 water)
	(has person24 medicine)
	(has person24 water)
	(has person25 medicine)
	(has person25 water)
	(has person26 medicine)
	(has person26 water)
	(has person27 medicine)
	(has person27 water)
	(has person28 medicine)
	(has person28 water)
	(has person29 medicine)
	(has person29 water)
	(has person30 water)
	))
)
